controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    elastoplastic_controller:
      type: elastoplastic_controller/ElastoplasticController

    robotiq_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController


robotiq_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: demo/robotiq_ft_sensor
    frame_id: demo/robotiq_ft_frame_id


joint_trajectory_controller:
  ros__parameters:
    joints:
      - demo/shoulder_pan_joint
      - demo/shoulder_lift_joint
      - demo/elbow_joint
      - demo/wrist_1_joint
      - demo/wrist_2_joint
      - demo/wrist_3_joint

    command_joints:
      - elastoplastic_controller/demo/shoulder_pan_joint
      - elastoplastic_controller/demo/shoulder_lift_joint
      - elastoplastic_controller/demo/elbow_joint
      - elastoplastic_controller/demo/wrist_1_joint
      - elastoplastic_controller/demo/wrist_2_joint
      - elastoplastic_controller/demo/wrist_3_joint

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity


elastoplastic_controller:
  ros__parameters:
    dt: 0.01 # <------------------------------ !!
    target_joint_trajectory_topic: "/joints_target"
    ft_sensor_name: demo/robotiq_ft_sensor
    frames:
      base: demo/base_footprint
      tool: demo/gripper/tcp
      sensor: demo/robotiq_ft_frame_id
    joints:
      - demo/shoulder_pan_joint
      - demo/shoulder_lift_joint
      - demo/elbow_joint
      - demo/wrist_1_joint
      - demo/wrist_2_joint
      - demo/wrist_3_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    floating_base:
      enabled: true
      input_target_topic: "/target_cmd_vel"
      odom: "/odom"
      max_vel:
        linear: [10.0, 10.0]
        angular: 1.0
    wrench_deadband: [1.0,0.0]
    impedance:
      inertia: [1.0, 1.0, 1.0]
      lugre:
        sigma_0: 100.0
        sigma_1: 50.0
        sigma_2: 10.0
        z_ss: 0.5
        z_ba: 0.1
      tau_w: 0.02
      reset_condition:
        reset_window_size: 2000
        reset_threshold: 0.01
    clik:
      kp: 10.0
      kv: 100.0
      task:
        alpha_gain: 1.0e5
        #weights: [100.0, 100.0, 100.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        #weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        weights: [1.0e-2, 1.0e-2, 1.0e-2, 1.0e0, 1.0e0, 1.0e0, 1.0e0, 1.0e0, 1.0e0]
        last:
          kp: 1.0e1
          kv: 1.0e2
    debug: true


cartesian_motion_controller:
  ros__parameters:
    end_effector_link: "demo/tool0"
    robot_base_link:   "demo/base_link"
    joints:
      - demo/shoulder_pan_joint
      - demo/shoulder_lift_joint
      - demo/elbow_joint
      - demo/wrist_1_joint
      - demo/wrist_2_joint
      - demo/wrist_3_joint

    # See the cartesian_compliance_controller
    command_interfaces:
      - position
        #- velocity

    solver:
        error_scale: 1.0
        iterations: 10
        publish_state_feedback: True

    pd_gains:
        trans_x: {p: 1.0}
        trans_y: {p: 1.0}
        trans_z: {p: 1.0}
        rot_x: {p: 0.5}
        rot_y: {p: 0.5}
        rot_z: {p: 0.5}
