controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    elastoplastic_controller:
      type: elastoplastic_controller/ElastoplasticController

    robotiq_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster


robotiq_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: robotiq_ft_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: robotiq_ft_frame_id


joint_trajectory_controller:
  ros__parameters:
    joints:
      - az_shoulder_pan_joint
      - az_shoulder_lift_joint
      - az_elbow_joint
      - az_wrist_1_joint
      - az_wrist_2_joint
      - az_wrist_3_joint
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity


elastoplastic_controller:
  ros__parameters:
    target_joint_trajectory_topic: "/joints_target"
    ft_sensor_name: "ft_sensor"
    frames:
      base: "base_link"
      tool: "tool0"
      sensor: "sensor"
    joints:
      - az_shoulder_pan_joint
      - az_shoulder_lift_joint
      - az_elbow_joint
      - az_wrist_1_joint
      - az_wrist_2_joint
      - az_wrist_3_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    floating_base:
      enabled: false
      input_target_topic: "/reference_cmd_vel"
      odom: "/odom"
    wrench_deadband: [1.0,0.0]
    impedance:
      inertia: [10.0, 10.0, 10.0]
      lugre:
        sigma_0: 1000.0
        sigma_1: 10.0
        sigma_2: 10.0
        z_ss: 0.5
        z_ba: 0.1
      tau_w: 0.02
      reset_condition:
        reset_window_size: 1000
        reset_threshold: 0.1
