controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    elastoplastic_controller:
      type: elastoplastic_controller/ElastoplasticController

    robotiq_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster


robotiq_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: az_robotiq_ft_sensor
    frame_id: az_robotiq_ft_frame_id


joint_trajectory_controller:
  ros__parameters:
    joints:
      - az_shoulder_pan_joint
      - az_shoulder_lift_joint
      - az_elbow_joint
      - az_wrist_1_joint
      - az_wrist_2_joint
      - az_wrist_3_joint

    command_joints:
      - elastoplastic_controller/az_shoulder_pan_joint
      - elastoplastic_controller/az_shoulder_lift_joint
      - elastoplastic_controller/az_elbow_joint
      - elastoplastic_controller/az_wrist_1_joint
      - elastoplastic_controller/az_wrist_2_joint
      - elastoplastic_controller/az_wrist_3_joint

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity


elastoplastic_controller:
  ros__parameters:
    target_joint_trajectory_topic: "/joints_target"
    ft_sensor_name: az_robotiq_ft_sensor
    frames:
      base: az_base_footprint
      tool: az_tool0
      sensor: az_robotiq_ft_frame_id
    joints:
      - az_shoulder_pan_joint
      - az_shoulder_lift_joint
      - az_elbow_joint
      - az_wrist_1_joint
      - az_wrist_2_joint
      - az_wrist_3_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    floating_base:
      enabled: true
      input_target_topic: "/target_cmd_vel"
      odom: "/odom"
    wrench_deadband: [1.0,0.0]
    impedance:
      inertia: [10.0, 10.0, 10.0]
      lugre:
        sigma_0: 100.0
        sigma_1: 10.0
        sigma_2: 50.0
        z_ss: 0.5
        z_ba: 0.1
      tau_w: 0.02
      reset_condition:
        reset_window_size: 1000
        reset_threshold: 0.1
    clik:
      kp: 0.001
      kd: 0.01
    debug: true
